### ISSUE TITLE
what happened?

### ISSUE THREAD

**Issue by daybugging** [gearsdigital/kirby-analytics-dashboard#1]
seriously?

**Comment by gearsdigital** [comment]
Lack of time @daybugging :(

**Comment by S1SYPHOS** [comment]
Well, why not dump what you have and tell people it's unmaintained, not ready for production, maybe someone will pick up where you left :+1:

**Comment by gearsdigital** [comment]
@S1SYPHOS I decided to pick up the work… I'll let you know if I'm ready to ship a version :)

**Comment by S1SYPHOS** [comment]
Sounds great!
