### ISSUE TITLE
Can't get it to work :(

### ISSUE THREAD

**Issue by wottpal** [gearsdigital/kirby-analytics-dashboard#1]
### Expected behavior and actual behavior.
Should show the Google login-button in the panel but the "Besucher" widget is just empty. And there is an error in the console `'gears' is not defined`.

<img width="1041" alt="bildschirmfoto 2018-01-09 um 15 06 48" src="https://user-images.githubusercontent.com/3930150/34724942-c7892088-f54f-11e7-8f75-3eb7985ff057.png">

### Steps to reproduce the problem.
I have installed the plugin, have done all the prerequisites & configured it.

### Specifications like the version of the project, operating system, or hardware.
Latest Kirby & Panel

**Comment by gearsdigital** [comment]
Hello @wottpal,

thank your very much for your request! Could you please add some details about your current environment? I cross checked it with latest Safari, Firefox and Chrome and everything seems to be working correctly… 🤔

It looks the namespace isn't loaded as expected.

**Comment by wottpal** [comment]
I am pretty much up to date. Running the latest macOS 10.13.2, the latest Safari & Chrome and my PHP version is 7.1.11. I get this issue with both browsers either on my local environment (localhost or custom vhost) and on my remote server. I have added both URLs as authorized JS-sources in the Google Developer Console.

**Comment by gearsdigital** [comment]
I'll take a look and come back to you when I found out what is going on here. Sorry for your inconveniences!

**Comment by wottpal** [comment]
I guess I solved it :) 
It was my fault, I installed it as a git submodule (what I always do with kirby plugins) but you haven't added the dist-files to the repo but only to the releases-download. Could you change that? Submodules make it way easier for updating & deploying things and it will prevent future confusions.

It works now properly and I love it so far 😍 
Thanks

**Comment by gearsdigital** [comment]
**Awesome!** I haven't thought about git-submodules yet. I'll take care about that issue within the next releases…

Thanks for the hint 👍

**Comment by gearsdigital** [comment]
@wottpal I pushed a [new release](https://github.com/gearsdigital/kirby-analytics-dashboard/releases/tag/v1.0.1) which targets your submodule issue.

**Comment by wottpal** [comment]
Thaaaanks! Can confirm that it's working now.
